import Head from 'next/head'
import Layout from '/components/Layout/Layout'
import Sidebar from '/components/UI/Sidebar'
import Main from '/components/UI/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>GMarket - Wallmart Store</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/icons/logo.png' />
      </Head>

      <Layout>
        <Sidebar />
        <Main />
      </Layout>
    </div>
  )
}
